// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFV73qBAP8Diezi0fHbH0WHmeKz8nKXyg',
    appId: '1:184793695165:web:8a28f0b7d495291fb008d4',
    messagingSenderId: '184793695165',
    projectId: 'flutter-application-residencia',
    authDomain: 'flutter-application-residencia.firebaseapp.com',
    storageBucket: 'flutter-application-residencia.appspot.com',
    measurementId: 'G-7XP2K38GGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLR3H7rO5LyY87llk7KIl6t75EPY4nSzU',
    appId: '1:184793695165:android:566f455461f05daab008d4',
    messagingSenderId: '184793695165',
    projectId: 'flutter-application-residencia',
    storageBucket: 'flutter-application-residencia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqm-K2ZGsKawLbG1P2zdXz-73bdAsDKg',
    appId: '1:184793695165:ios:1db814e8de2c9482b008d4',
    messagingSenderId: '184793695165',
    projectId: 'flutter-application-residencia',
    storageBucket: 'flutter-application-residencia.appspot.com',
    iosClientId: '184793695165-ahngl5po0qun2rj41gk8kouhqf4bot5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpqm-K2ZGsKawLbG1P2zdXz-73bdAsDKg',
    appId: '1:184793695165:ios:0fa80031fa51ac64b008d4',
    messagingSenderId: '184793695165',
    projectId: 'flutter-application-residencia',
    storageBucket: 'flutter-application-residencia.appspot.com',
    iosClientId: '184793695165-k5bske0jlk0gdl0lkjc8gv8g7m0ejqlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
